const express = require('express');
const PDFDocument = require('pdfkit');
const path = require('path');

const app = express();
const PORT = 3000;

// Middleware
app.use(express.json());
app.use(express.static('.')); // Serve current directory

// PDF Generation Endpoint
app.get('/generate-pdf-report', (req, res) => {
    try {
        const { accNo, transactionId, amount, location, riskScore, alerts } = req.query;
        
        const doc = new PDFDocument();
        
        // Set response headers
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=fraud-report-${transactionId}.pdf`);
        
        // Pipe PDF to response
        doc.pipe(res);
        
        // Add content to PDF
        doc.fillColor('#2c3e50')
           .fontSize(20)
           .text('FRAUD DETECTION SYSTEM REPORT', 100, 100, { align: 'center' });
        
        doc.fillColor('#666')
           .fontSize(12)
           .text(`Generated on: ${new Date().toLocaleString()}`, 100, 130, { align: 'center' });
        
        // Transaction Details
        doc.fillColor('#2c3e50')
           .fontSize(16)
           .text('TRANSACTION DETAILS', 100, 180);
        
        doc.fillColor('#333')
           .fontSize(12)
           .text(`Account Number: ${accNo}`, 100, 210)
           .text(`Transaction ID: ${transactionId}`, 100, 230)
           .text(`Amount: $${parseFloat(amount).toLocaleString()}`, 100, 250)
           .text(`Location: ${location}`, 100, 270)
           .text(`Risk Score: ${riskScore}%`, 100, 290);
        
        // Security Analysis
        doc.fillColor('#2c3e50')
           .fontSize(16)
           .text('SECURITY ANALYSIS', 100, 330);
        
        let yPosition = 360;
        if (alerts && alerts.length > 0) {
            alerts.split(',').forEach(alert => {
                doc.fillColor('#e74c3c')
                   .fontSize(11)
                   .text(`• ${alert.trim()}`, 120, yPosition);
                yPosition += 20;
            });
        } else {
            doc.fillColor('#27ae60')
               .fontSize(11)
               .text('• No security threats detected', 120, yPosition);
        }
        
        // Footer
        doc.fillColor('#999')
           .fontSize(10)
           .text('Generated by Advanced Fraud Detection System - Confidential Report', 
                 100, 750, { align: 'center' });
        
        doc.end();
        
    } catch (error) {
        console.error('PDF generation error:', error);
        res.status(500).json({ error: 'Failed to generate PDF' });
    }
});

// SMS Alert Endpoint (Simulated)
app.post('/send-sms-alert', (req, res) => {
    try {
        const { phoneNumber, message, transactionDetails } = req.body;
        
        console.log('📱 SMS Alert Details:');
        console.log('To:', phoneNumber);
        console.log('Message:', message);
        console.log('Transaction:', transactionDetails);
        
        // Simulate SMS sending
        res.json({
            success: true,
            message: `SMS alert sent to ${phoneNumber}`,
            timestamp: new Date().toISOString(),
            simulated: true
        });
        
    } catch (error) {
        console.error('SMS sending error:', error);
        res.status(500).json({ error: 'Failed to send SMS' });
    }
});

// Email Report Endpoint (Simulated)
app.post('/send-email-report', (req, res) => {
    try {
        const { email, subject, reportData } = req.body;
        
        console.log('📧 Email Alert:');
        console.log('To:', email);
        console.log('Subject:', subject);
        console.log('Report Data:', reportData);
        
        res.json({
            success: true,
            message: `Report sent to ${email}`,
            timestamp: new Date().toISOString()
        });
        
    } catch (error) {
        console.error('Email sending error:', error);
        res.status(500).json({ error: 'Failed to send email' });
    }
});

// Serve the HTML file
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(PORT, () => {
    console.log(`🚀 Fraud Detection System running on http://localhost:${PORT}`);
});
